import {
  DeleteOutline,
  FolderOutline,
  ScanOutline,
  ProfileOutline,
  ReloadOutline,
  ShakeOutline,
  WechatOutline,
  SendOutline,
  CloudUploadOutline,
  HomeOutline,
  RollbackOutline,
  ShareAltOutline,
  LoadingOutline,
  FileTwoTone,
  ClearOutline,
  DownloadOutline,
  PictureTwoTone,
} from '@ant-design/icons-angular/icons';

export const antDesignIcons = [
  DeleteOutline,
  FolderOutline,
  ScanOutline,
  ProfileOutline,
  ReloadOutline,
  ShakeOutline,
  WechatOutline,
  SendOutline,
  CloudUploadOutline,
  HomeOutline,
  RollbackOutline,
  ShareAltOutline,
  LoadingOutline,
  FileTwoTone,
  ClearOutline,
  DownloadOutline,
  PictureTwoTone,
];
